# Generated by Django 2.1.5 on 2019-03-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('SERVICE', 'SERVICE'), ('SPARE', 'SPARE')], max_length=200)),
                ('address', models.TextField()),
            ],
        ),
    ]
