# Generated by Django 2.1.5 on 2019-03-15 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Spares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spare_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('per_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('suppliers', models.CharField(max_length=200)),
                ('quality_class', models.CharField(choices=[('FIRST', 'FIRST'), ('SECOND', 'SECOND'), ('SECOND', 'SECOND')], max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Brand')),
                ('brand_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.BrandModel')),
            ],
        ),
    ]
