# Generated by Django 2.1.5 on 2019-03-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spares',
            name='per_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
