# Generated by Django 2.1.5 on 2019-03-16 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20190315_1204'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spares',
            new_name='Spare',
        ),
    ]
