# Generated by Django 2.1.5 on 2019-04-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_sparecustomer_spareorder_sparesold'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparesold',
            name='spare_buying_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
