# Generated by Django 2.1.5 on 2019-03-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20190316_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare',
            name='quality_class',
            field=models.CharField(choices=[('FIRST', 'FIRST'), ('SECOND', 'SECOND'), ('THIRD', 'THIRD')], max_length=100),
        ),
    ]
