# Generated by Django 2.1.5 on 2019-04-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_sparesold_spare_buying_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare',
            name='is_urgent_spare',
            field=models.BooleanField(default=False),
        ),
    ]
