# Generated by Django 2.1.5 on 2019-03-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20190316_0714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='brandmodel',
            options={'ordering': ['model_name']},
        ),
        migrations.AlterModelOptions(
            name='spare',
            options={'ordering': ['spare_name']},
        ),
        migrations.AddField(
            model_name='spare',
            name='spare_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
