# Generated by Django 2.1.5 on 2019-04-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_spare_is_urgent_spare'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare',
            name='spare_location',
            field=models.CharField(default='', max_length=500),
        ),
    ]
