# Generated by Django 2.1.5 on 2019-03-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20190316_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare',
            name='spare_local_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='spare',
            name='quality_class',
            field=models.CharField(max_length=100),
        ),
    ]
