# Generated by Django 2.1.5 on 2019-04-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_spare_spare_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='spareorder',
            name='bike_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='spareorder',
            name='labour_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='spareorder',
            name='out_source_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
