# Generated by Django 2.1.5 on 2019-04-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20190403_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare',
            name='spare_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='spare',
            name='spare_location',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
