# Generated by Django 2.1.5 on 2019-03-18 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_labour'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerComplaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='servicecost',
            name='service_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='service.ServiceType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generalservicetestresults',
            name='status',
            field=models.CharField(choices=[('WORKING', 'WORKING'), ('NOT_WORKING', 'NOT_WORKING'), ('REPLACE', 'REPLACE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('LIVE', 'LIVE'), ('COMPLETED', 'COMPLETED'), ('DELIVERED', 'DELIVERED')], default='NEW', max_length=20),
        ),
        migrations.AddField(
            model_name='customercomplaints',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Service'),
        ),
    ]
